### ISSUE TITLE
Không đọc được hết các bản ghi trong database

### ISSUE THREAD

**Issue by haprosd5** [uit2712/SQLite-in-React-Native#1]
Em chào anh ạ, anh ơi em có tham khảo video sử dụng sqlite của anh trên youtube. Nhưng hiện tại e đang gặp một vấn đề là ko đọc được hết các bản ghi trong bảng user.Anh có thể giúp e được ko ạ

**Comment by uit2712** [comment]
@haprosd5 mình chưa hiểu ý bạn lắm? "ko đọc được hết các bản ghi trong bảng user" là sao nhỉ?

**Comment by haprosd5** [comment]
Sau khi gặp lỗi mình chuyển qua dùng thằng realm rồi bạn ạ. Thấy nhanh hơn,
đỡ lỗi hơn rồi

Vào Th 7, 10 thg 11, 2018 vào lúc 11:36 uit2712 <notifications@github.com>
đã viết:

**Comment by haprosd5** [comment]
Thank bạn nhé!!
Mình sau khi gặp lỗi dùng sqlit thì chuyển qua realm dùng bạn ạ :))))
Ít lỗi và nhiều hướng dẫn hơn hẳn.

Vào 11:10, T.7, 17 Th11, 2018 hong ha ta <haprosd5@gmail.com đã viết:
